### ISSUE TITLE
Soft delete articles

### ISSUE THREAD

**Issue by vpmalley** [vpmalley/jetlag#13]
The articles might better be recoverable when deleted by a user, instead of deleting them forever.

**Comment by Vallenain** [comment]
At work we never delete objects, instead we set their _is_deleted field to true. Maybe a similar solution could be used here. And then any request knows it should not consider objects with _is_deleted=true.
For the user, it's completely transparent, for us, it's easier to debug or to retrieve stuff that should have not been deleted.

**Comment by vpmalley** [comment]
Yeah, exactly, that's the cool thing to do. Laravel does this by setting the deleted_at field with the deletion date. It's pretty cool that they directly provide that feature.
http://laravel.com/docs/5.1/eloquent#soft-deleting

**Comment by vpmalley** [comment]
Enabled soft delete on
- Article
- Map
- Picture
