### ISSUE TITLE
Create a UserPublic when a user registers

### ISSUE THREAD

**Issue by vpmalley** [vpmalley/jetlag#14]
In Jetlag, a user is represented in 2 different DB tables, matched by 2 objects. A User is only used for authentication so far and later for private data, while the UserPublic contains the public data. Both objects have the same id in DB. When registering, a User is created and persisted but not a UserPublic. One should be created and persisted in order to make sure the ids match.

**Comment by vpmalley** [comment]
Also, the persistence of both should be ideally done within one transaction.

**Comment by Vallenain** [comment]
Is that a Laravel limitation or a choice of design ?
But I do agree that if the two objects are strongly linked, they must be persisted in the same transaction (and so failure on one would ensure the failure of the other)

**Comment by vpmalley** [comment]
That was my choice, actually. The reason to split a user's data in two objects was to split "private" and "public" data.
Practically, this meant that requests to a user's private data are only done when the user is logging in. When displaying a user profile, the public data is enough.
