### ISSUE TITLE
Have consistent naming for DB/REST fields

### ISSUE THREAD

**Issue by vpmalley** [vpmalley/jetlag#26]
Use consistent naming (either myField or my_field ) for all fields. So far there is a mix and it is confusing. Choose for both the REST API and the DB.

**Comment by Vallenain** [comment]
I let this decision to you and will make the JS model part match the convention. I think the underscore convention is more readable but can lead to very long names. Up to you :)

**Comment by vpmalley** [comment]
OK, I was going for that too just because Laravel picked this convention so need to override all the names they chose.
So, go for underscores, unless you prefer the other

**Comment by Vallenain** [comment]
Underscores it is !
