### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#34]
Big part including both server side code and front side. Several points to discuss: how should the API endpoint look ? Where do we search by default (titles, content) and what content (paragraphs, articles, travelbooks) ?

(We may want split this issue in two)

**Comment by vpmalley** [comment]
And how do we sort the results?
Maybe we can look into elasticsearch or similar search tools that are integrated with Laravel (maybe Eloquent already has such a feature).

**Comment by vpmalley** [comment]
see http://tnt.studio/blog/searching-for-bobby-fisher-with-laravel-5
This is a package pluggable in Laravel that indexes documents for search

**Comment by Vallenain** [comment]
It seems to be a pretty good tool ! I've heard too many times that people were using elastic search when simpler tools were available and actually better suited their needs.

**Comment by vpmalley** [comment]
I used the tntsearch to implement some basic search feature.
It searches on the title, the description for now. It is a SQL query to update to fix it.
It lets everyone search on everyone's private articles too.
Also I should write some minimum doc for later maintenance/improvement

**Comment by Vallenain** [comment]
What's the endpoint name ?

**Comment by vpmalley** [comment]
Oh right I did not say it. It is:
GET api/0.1/search/articles
with the query parameter "query".
e.g. _GET api/0.1/search/articles?query=beach_

**Comment by Vallenain** [comment]
Actually, after thinking a bit on the subject, would it be possible to simply have `/api/0.1/articles?query=beach`. It would make equivalent `api/0.1/articles?query=` and `api/0.1/articles` which, I think, makes sense.  
Anyway, for now, I've implemented the search with the URL you've provided but if that's not too complicated and, most important, if you also think it'd be preferable to have a single endpoint name, let's move to the second option asap :) (not tested though, because of #45 )

**Comment by vpmalley** [comment]
Yeah ok we could do this second option

**Comment by vpmalley** [comment]
I forgot: to index the articles in the first place, run:
`php artisan index:articles`

**Comment by Vallenain** [comment]
https://github.com/vpmalley/jetlag/wiki/DevCheatSheet#indexing-articles

**Comment by Vallenain** [comment]
Search seems to work but I'm not sure how: if I type 'pleas' I get no results whereas if I type 'pleasing' I get two articles. I guess it only looks for perfect matches at the word scale.

**Comment by vpmalley** [comment]
index should be updated on article creation/update/deletion

**Comment by vpmalley** [comment]
for some reason the issue regarding the database file that cannot be open is due to the storage path not writable (which is weird since it does have the rights for the vagrant user).

Anyway I also created an environment variable called `SEARCH_INDEX_LOC`. If set, this path  will be used for indices (and you should create that folder and have the correct rights on it). If not, the `storage_path()` will be used.
