### ISSUE TITLE
How (and where) to deal with unexpected attributes ?

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#35]
Angular may add some properties to javascript objects (mostly, stuff starting with '$$...'). For now it is sent to the server as part of the objects.
In the future, we also may add some properties only used on front-side.

Question is: should we only send to the server the properties it expects, or is it able to handle some extra properties (that it won't read and won't attach to the server-side object).

@vpmalley Open question since it is probably not too hard to remove those properties before to send the object.

**Comment by vpmalley** [comment]
Good question, I would say for now it is fine to send them, as long as there is no trying to decode them on the server, and as long as it is not sensitive data. But yeah, that's a good open question.

**Comment by Vallenain** [comment]
The new custom library to manager models on front side only send the attributes which are clearly defined as part of the model (the ones in its schema). So we're good :)
