### ISSUE TITLE
Redirection after login should not consider API requests

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#43]
At the moment when I go to the homepage, I can't get some articles cause I'm not logged in. So I log in and then I'm redirected to /api/0.1/articles. 
Could you confirm the redirection is made on server side ? Would it be possible to redirect to a non-API request ? Maybe, if that helps, we can add a referer/backTo/whateverthename parameter in the url so the server know where to redirect.  
e.g. /auth/login?redirectTo=home

**Comment by vpmalley** [comment]
Yeah I think we already had the issue., let's handle redirection like you suggest, "redirectTo" sounds good.

**Comment by vpmalley** [comment]
OK, you can now add the query param `redirectTo` to any url that has the "guest" middleware, i.e. any url that might get redirected if the user is logged in. 

For example, if you are logged in, going to `/auth/login?redirectTo=/api/articles/1` will directly bring you to the article content.

Watch out, it might be fragile, I don't know all the protections I should add. You cannot redirect endlessly (i.e. `/auth/login?redirectTo=/auth/login` does not loop forever), but there might be other issues.

**Comment by vpmalley** [comment]
Also, if the login is required by a middleware, then after being logged in, the user is supposed to be redirected to the original page. If the login page is requested, the user will be redirected to the home page once authenticated.
