### ISSUE TITLE
Integers are returned instead of booleans in the API

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#44]
For example when calling the articles API, I got this `"isDraft":1,"isPublic":0`, would it be possible to have `true`/`false` instead ?

**Comment by vpmalley** [comment]
yes it is, I'll do it soon
cf. https://laravel.com/docs/5.2/eloquent-mutators#attribute-casting

**Comment by vpmalley** [comment]
I tried to fix it but I cannot test, let me know if that works

**Comment by vpmalley** [comment]
it will be fixed during a larger refactoring to remove Business\Article, keeping only Eloquent\Article.
