### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#48]
The search from homepage seems to be broken
I got a error 500 when calling this endpoint `http://homestead.app/api/0.1/search/articles?query=santiago`

**Comment by vpmalley** [comment]
I fixed something related to that, let me know if that happens again and tell me about the error message in this case.

**Comment by Vallenain** [comment]
Still there. The problem comes from the line 26 of ArticleSearch.php, it doesn't know the `??` operator (and to be fair, me neither 😄 - php 5.6)

**Comment by vpmalley** [comment]
Ah yeah what is your version of php? I hesitated to upgrade to Laravel 5.3 but php 5.6.4 is required. I don't need to upgrade yet but that'd be good to know.

**Comment by vpmalley** [comment]
OK I just removed these double question mark, let me know if that's fine now

**Comment by vpmalley** [comment]
Is it all right now?

**Comment by Vallenain** [comment]
Yes it seems to work fine ! Well done !
