### ISSUE TITLE
HTTP 400 when creating new article

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#49]
I might do things wrong but when creating a new article (POST request on /api/0.1/articles), I get this HTTP 400 error. My payload is:
```
authorUsers:[]
descriptionPicture:null
descriptionText:""
id:null
is_draft:true
is_public:false
paragraphs:[]
title:""
travelbook:{id: 1}
url:""
```
![capture](https://cloud.githubusercontent.com/assets/5220393/19902852/9964450e-a06c-11e6-9cf6-0ed5b624f162.PNG)

**Comment by vpmalley** [comment]
Yeah, the constraint not met is the title that is required to have at least 3 characters.

You can see and update the constraints in Jetlag\Business\Article:
`static $creationRules = [
    'title' => 'required|min:3|max:200',
    'description_text' => 'max:500',
    'descriptionMediaUrl' => 'max:200',
    'is_draft' => 'boolean',
  ];`
