### ISSUE TITLE
An article should only check required fields at publication time

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#64]
When creating a draft, and because of auto-saving, the article won't have any title for example, and there will still be some PUT requests to add paragraphs. For now those requests fail because of the field requirement.  
So I think those requirements should only be met when is_draft is set to false.

**Comment by vpmalley** [comment]
You're right, actually we can even go further and say it never checks anything, that's up to the "business" level to check it and therefore every endpoint checks it's own constraints.

**Comment by vpmalley** [comment]
I removed all constraints on the required contents and the minimum length of strings that were not really necessary. It should be up to the controller to check for the right constraints
