### ISSUE TITLE
Remove redirection to /traveller/id/edit when trying to get home page

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#9]
I'd like to be able to see the home page while being connected, I tried to comment the lines in the middleware but it makes a infinite redirection.

I'd need to dig deeper in the Laravel mechanisms to understand how to do it, and I think it'd be a way faster if you do it :)

**Comment by vpmalley** [comment]
You suspected the right place to make the change. This happens in the middleware Jetlag\Http\Middleware\RedirectIfAuthenticated, I changed to redirect to the home page when the user is authenticated. If you want to remove any redirection, either remove the body of the handle method of this middleware, or remove `$this->middleware('guest');` from the HomeController
